.PHONY: clean All

All:
	@echo "==========Building project:[ rock_scissor_papper - Debug ]=========="
	@cd "rock_scissor_papper" && "$(MAKE)" -f  "rock_scissor_papper.mk"
clean:
	@echo "==========Cleaning project:[ rock_scissor_papper - Debug ]----------"
	@cd "rock_scissor_papper" && "$(MAKE)" -f  "rock_scissor_papper.mk" clean
